# Generated by Django 4.0.5 on 2022-06-16 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occuppant_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('occupant_job', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=5)),
                ('room_type', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('price', models.FloatField(default=1000.0)),
                ('no_of_night', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_day', models.DateField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer_app.roommanager')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer_app.customer')),
            ],
        ),
    ]
