# Generated by Django 4.0.5 on 2022-06-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_app', '0001_initial'),
        ('Booking_app', '0003_alter_contact_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
