# Generated by Django 4.0.5 on 2022-06-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking_app', '0004_rename_rooms_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amount_paid',
            field=models.IntegerField(default=1),
        ),
    ]
