# Generated by Django 4.0.5 on 2022-06-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking_app', '0006_alter_room_amount_paid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
