# Generated by Django 4.0.5 on 2022-06-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking_app', '0007_delete_contact_delete_room'),
        ('Customer_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='RoomManager',
        ),
    ]
